version: '3.8'


services:
  commissionn-module:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: commissionn-module
    ports:
      - 8071:8071
    restart: always
    environment:
      - APP_ENV=stage
      - API_TOKEN=7tf4ghq5modr2zelxmr8wertbd6tp0d2
      - APP_PORT=:8094
      - SHH_PATH=/root/.ssh/id_rsa
